### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dbof10** [mo10/osu-visualizer#1]
the visualizer doesn't work when I tried to run it's just the background and the logo but not the visualizer

**Comment by mo10** [comment]
Hello,

Thank you for your interest in this repository. This repository is just my impromptu idea. It has stopped development. The visualization of OSU! is very cool, but I am not good at audio and visualization.

**Comment by dbof10** [comment]
I agreed. Did it ever work before or it's just in the middle of development?

**Comment by mo10** [comment]
No, it only show the effect of the bar.Maybe I should compile an osu! with only the player and visualization!:)
